name: Deploy Firebase on master

on:
  push:
    branches: [ master ]

permissions:
  contents: read
  id-token: write   # for workload identity auth (optional if you use service account key)

env:
  # Set your project ID here or as a secret
  FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Enable Corepack (Yarn Berry)
        run: |
          corepack enable
          corepack prepare yarn@3.8.5 --activate
          yarn config set nodeLinker node-modules
          yarn -v

      - name: Install dependencies
        run: yarn install --immutable

      # Deploy what you need:
      # hosting, firestore rules, realtime db rules, functions, storage rules, etc.
      - name: Deploy to Firebase
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        run: |
          yarn firebase deploy \
            --project "$FIREBASE_PROJECT_ID"
